# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=250)),
                ('edad', models.CharField(choices=[('0-14', '0-14'), ('15-24', '15-24'), ('25-34', '25-34'), ('35-54', '35-54'), ('55-80', '55-80'), ('80 y más', '80 y mas')], default='0-14', max_length=10)),
                ('poblacion_año', models.CharField(choices=[('2011', '2011'), ('2015', '2015')], default='2011', max_length=5)),
                ('numero_poblacion', models.IntegerField(default=0)),
            ],
        ),
    ]
